name: Feature Request
description: Suggest an enhancement to this development template
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! This template is for **improving the development template itself**, not integrations built from it.

        **Examples of template features:**
        - New example integration (OAuth2, multi-platform, services)
        - Additional documentation or guides
        - New development tools or scripts
        - CI/CD improvements
        - Better testing utilities

        **Not for this template:** Features for YOUR integration → implement in your own repository

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of enhancement is this?
      options:
        - "Example Integration (new reference implementation)"
        - "Documentation (guides, tutorials, wiki)"
        - "Development Tools (scripts, utilities, automation)"
        - "Testing (fixtures, helpers, patterns)"
        - "CI/CD (workflows, quality checks)"
        - "Project Structure (organization, boilerplate)"
        - "Other"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve for template users?
      placeholder: |
        Examples:
        - "Developers struggle to understand OAuth2 patterns because there's no example"
        - "The testing guide doesn't show how to mock websockets"
        - "No guidance on implementing multi-device hubs"
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: What specifically should be added to the template?
      placeholder: |
        Examples:
        - "Add custom_components/example_oauth2_integration/ with working OAuth2 flow"
        - "Create docs/WEBSOCKET_TESTING.md with mock examples"
        - "Add hub example with device discovery pattern"

        Be specific about files, documentation, or tools to add.
    validations:
      required: true

  - type: textarea
    id: benefit
    attributes:
      label: Who Benefits?
      description: Which developers would find this useful?
      placeholder: |
        Examples:
        - "Developers integrating cloud services with OAuth2"
        - "Anyone building real-time integrations"
        - "Developers creating hub integrations (Philips Hue, Zigbee, etc.)"
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Examples or References
      description: Links to similar implementations or documentation
      placeholder: |
        Examples:
        - "HA Core Nest integration uses this pattern: https://..."
        - "Similar to how the Spotify integration handles this"
        - "See this guide: https://..."
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this to HA integration development?
      options:
        - "High - Common pattern needed by many integrations"
        - "Medium - Useful for specific integration types"
        - "Low - Nice to have but not critical"
    validations:
      required: false

  - type: checkboxes
    id: quality-tier
    attributes:
      label: Quality Scale Impact
      description: Which quality tiers does this help achieve?
      options:
        - label: "Bronze - Basic functionality"
        - label: "Silver - Reliability and error handling"
        - label: "Gold - Testing and async patterns"
        - label: "Platinum - Code excellence and performance"

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Can you help make this happen?
      options:
        - label: "I can submit a PR with this feature"
        - label: "I can provide example code or patterns"
        - label: "I can help review and test"
        - label: "I can contribute documentation"

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other details, mockups, or examples
      placeholder: |
        - Code snippets showing the pattern
        - Links to discussions or issues
        - Screenshots of desired output
