blueprint:
  name: Adaptive Lighting with Verification
  description: >-
    Automatically adjusts light color temperature and brightness throughout the
    day based on sun position. Uses Light Controller's verification to ensure
    lights reach the target state. Only adjusts lights that are currently on.
  domain: automation
  author: Light Controller
  source_url: https://github.com/your-repo/light-controller/blueprints/adaptive_lighting.yaml

  input:
    target_lights:
      name: Target Lights
      description: Lights or light groups to adaptively control
      selector:
        entity:
          domain: light
          multiple: true

    update_interval:
      name: Update Interval
      description: How often to update the lights (in minutes)
      default: 15
      selector:
        number:
          min: 5
          max: 60
          step: 5
          unit_of_measurement: "min"

    min_brightness:
      name: Minimum Brightness (Night)
      description: Brightness at night (sun far below horizon)
      default: 30
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"
          mode: slider

    max_brightness:
      name: Maximum Brightness (Day)
      description: Brightness during the day
      default: 100
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"
          mode: slider

    min_kelvin:
      name: Warmest Color Temperature (Night)
      description: Color temperature at night (warm)
      default: 2200
      selector:
        number:
          min: 1800
          max: 4000
          unit_of_measurement: "K"

    max_kelvin:
      name: Coolest Color Temperature (Day)
      description: Color temperature during the day (cool)
      default: 5500
      selector:
        number:
          min: 4000
          max: 6500
          unit_of_measurement: "K"

    transition:
      name: Transition Time
      description: Time in seconds for gradual changes
      default: 30
      selector:
        number:
          min: 0
          max: 120
          step: 5
          unit_of_measurement: "s"

    only_update_on_lights:
      name: Only Update Lights That Are On
      description: If disabled, will also turn on lights that are off
      default: true
      selector:
        boolean:

    disable_switch:
      name: Disable Switch (optional)
      description: >-
        Input boolean to disable adaptive lighting. When on, automation is disabled.
        Leave empty for no disable switch.
      default: {}
      selector:
        entity:
          domain: input_boolean

mode: single
max_exceeded: silent

trigger:
  - platform: time_pattern
    minutes: !input update_interval

  - platform: state
    entity_id: sun.sun

variables:
  min_bri: !input min_brightness
  max_bri: !input max_brightness
  min_k: !input min_kelvin
  max_k: !input max_kelvin
  trans: !input transition
  only_on: !input only_update_on_lights
  disable_entity: !input disable_switch

  # Sun elevation (-90 to 90 degrees)
  sun_elevation: "{{ state_attr('sun.sun', 'elevation') | float(0) }}"

  # Normalize sun elevation to 0-1 scale
  # Below horizon (< 0): map -18 to 0 => 0 to 0.3
  # Above horizon (>= 0): map 0 to 60 => 0.3 to 1
  sun_factor: >-
    {% if sun_elevation < -18 %}
      0
    {% elif sun_elevation < 0 %}
      {{ ((sun_elevation + 18) / 18) * 0.3 }}
    {% elif sun_elevation < 60 %}
      {{ 0.3 + ((sun_elevation / 60) * 0.7) }}
    {% else %}
      1
    {% endif %}

  # Calculate brightness (interpolate between min and max)
  calc_brightness: >-
    {{ (min_bri + (sun_factor * (max_bri - min_bri))) | round(0) | int }}

  # Calculate color temperature (interpolate between warm and cool)
  calc_kelvin: >-
    {{ (min_k + (sun_factor * (max_k - min_k))) | round(0) | int }}

condition:
  # Check disable switch
  - condition: template
    value_template: >-
      {% if disable_entity %}
        {{ not is_state(disable_entity, 'on') }}
      {% else %}
        true
      {% endif %}

action:
  # Get list of lights that are currently on (if only_on is true)
  - variables:
      lights_to_update: >-
        {% if only_on %}
          {% set on_lights = expand(target_lights) | selectattr('state', 'eq', 'on') | map(attribute='entity_id') | list %}
          {{ on_lights }}
        {% else %}
          {{ target_lights }}
        {% endif %}

  # Only proceed if there are lights to update
  - condition: template
    value_template: "{{ lights_to_update | length > 0 }}"

  - service: light_controller.ensure_state
    data:
      entities: "{{ lights_to_update }}"
      state: "on"
      brightness_pct: "{{ calc_brightness }}"
      color_temp_kelvin: "{{ calc_kelvin }}"
      transition: "{{ trans }}"
      skip_verification: true  # Fire-and-forget for adaptive updates
