blueprint:
  name: Button/Remote Scene Controller
  description: >-
    Maps button presses from a wall remote, switch, or any event entity to
    light scenes with verification and retry. Supports up to 4 buttons/scenes.
    Each button activates a specific brightness and color configuration.
  domain: automation
  author: Light Controller
  source_url: https://github.com/your-repo/light-controller/blueprints/button_scene_controller.yaml

  input:
    # Button inputs
    button_1:
      name: Button 1 Entity
      description: First button/event entity (required)
      selector:
        entity:
          domain:
            - event
            - binary_sensor
            - input_button

    button_2:
      name: Button 2 Entity (optional)
      description: Second button/event entity. Leave empty to skip.
      default: {}
      selector:
        entity:
          domain:
            - event
            - binary_sensor
            - input_button

    button_3:
      name: Button 3 Entity (optional)
      description: Third button/event entity. Leave empty to skip.
      default: {}
      selector:
        entity:
          domain:
            - event
            - binary_sensor
            - input_button

    button_4:
      name: Button 4 Entity (optional)
      description: Fourth button/event entity. Leave empty to skip.
      default: {}
      selector:
        entity:
          domain:
            - event
            - binary_sensor
            - input_button

    # Target lights
    target_lights:
      name: Target Lights
      description: Lights or light groups to control
      selector:
        entity:
          domain: light
          multiple: true

    # Scene configurations
    scene_1_brightness:
      name: Scene 1 Brightness
      description: Brightness for button 1 (e.g., Daytime)
      default: 100
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"
          mode: slider

    scene_1_kelvin:
      name: Scene 1 Color Temperature
      description: Color temperature for button 1. Set to 0 for no color temp.
      default: 4000
      selector:
        number:
          min: 0
          max: 6500
          unit_of_measurement: "K"

    scene_2_brightness:
      name: Scene 2 Brightness
      description: Brightness for button 2 (e.g., Evening)
      default: 60
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"
          mode: slider

    scene_2_kelvin:
      name: Scene 2 Color Temperature
      description: Color temperature for button 2
      default: 2700
      selector:
        number:
          min: 0
          max: 6500
          unit_of_measurement: "K"

    scene_3_brightness:
      name: Scene 3 Brightness
      description: Brightness for button 3 (e.g., Bedtime)
      default: 20
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"
          mode: slider

    scene_3_kelvin:
      name: Scene 3 Color Temperature
      description: Color temperature for button 3
      default: 2200
      selector:
        number:
          min: 0
          max: 6500
          unit_of_measurement: "K"

    scene_4_brightness:
      name: Scene 4 Brightness
      description: Brightness for button 4 (e.g., Cleaning)
      default: 100
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"
          mode: slider

    scene_4_kelvin:
      name: Scene 4 Color Temperature
      description: Color temperature for button 4
      default: 5000
      selector:
        number:
          min: 0
          max: 6500
          unit_of_measurement: "K"

    # Common settings
    transition:
      name: Transition Time
      description: Time in seconds to transition between scenes
      default: 0.5
      selector:
        number:
          min: 0
          max: 10
          step: 0.1
          unit_of_measurement: "s"

    max_retries:
      name: Max Retries
      description: Maximum retry attempts if lights fail
      default: 3
      selector:
        number:
          min: 1
          max: 10
          step: 1

mode: queued
max_exceeded: silent
max: 5

trigger:
  - platform: state
    entity_id: !input button_1
    id: button_1

  - platform: state
    entity_id: !input button_2
    id: button_2

  - platform: state
    entity_id: !input button_3
    id: button_3

  - platform: state
    entity_id: !input button_4
    id: button_4

variables:
  trans: !input transition
  retries: !input max_retries
  # Scene configs
  s1_bri: !input scene_1_brightness
  s1_k: !input scene_1_kelvin
  s2_bri: !input scene_2_brightness
  s2_k: !input scene_2_kelvin
  s3_bri: !input scene_3_brightness
  s3_k: !input scene_3_kelvin
  s4_bri: !input scene_4_brightness
  s4_k: !input scene_4_kelvin

action:
  - choose:
      - conditions:
          - condition: trigger
            id: button_1
        sequence:
          - service: light_controller.ensure_state
            data:
              entities: !input target_lights
              state: "on"
              brightness_pct: "{{ s1_bri }}"
              color_temp_kelvin: "{{ s1_k if s1_k > 0 else none }}"
              transition: "{{ trans }}"
              max_retries: "{{ retries }}"

      - conditions:
          - condition: trigger
            id: button_2
        sequence:
          - service: light_controller.ensure_state
            data:
              entities: !input target_lights
              state: "on"
              brightness_pct: "{{ s2_bri }}"
              color_temp_kelvin: "{{ s2_k if s2_k > 0 else none }}"
              transition: "{{ trans }}"
              max_retries: "{{ retries }}"

      - conditions:
          - condition: trigger
            id: button_3
        sequence:
          - service: light_controller.ensure_state
            data:
              entities: !input target_lights
              state: "on"
              brightness_pct: "{{ s3_bri }}"
              color_temp_kelvin: "{{ s3_k if s3_k > 0 else none }}"
              transition: "{{ trans }}"
              max_retries: "{{ retries }}"

      - conditions:
          - condition: trigger
            id: button_4
        sequence:
          - service: light_controller.ensure_state
            data:
              entities: !input target_lights
              state: "on"
              brightness_pct: "{{ s4_bri }}"
              color_temp_kelvin: "{{ s4_k if s4_k > 0 else none }}"
              transition: "{{ trans }}"
              max_retries: "{{ retries }}"
